name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: install lld
      run: sudo apt-get install lld
    - name: test
      run: make test CC=clang LD=wasm-ld JS=node
